### PR TITLE
issue 9635

### PR DESCRIPTION
**Pull request by inkz**
added ExactDelay object for NodeJS vuln checking #9635

### CODE REVIEW

**Comment by andresriancho** [comment]
@inkz: Your pull request was incorrectly created. Looks like you did this:
 * git clone ...
 * Modify w3af's source code
 * Create pull request from your code to w3af's develop branch. This will merge some changes from master to develop and potentially create some issues.

When you should have done [this](https://github.com/andresriancho/w3af/wiki/Contributing-101).

Note that your next pull request should only have commits you authored.

**Comment by andresriancho** [comment]
[Your change](https://github.com/inkz/w3af/commit/2488fb2763b4bbd74c8d049a633c6a06cd7340e5) looks good . I believe it will be accepted if the future pull request is correct.

**Comment by andresriancho** [comment]
Did you test the `ExactDelay` line you added in a real-life nodejs application? Could you share the vulnerable application used? Finally, could you create a Dockerfile which we can use to run the nodejs application?

**Comment by inkz** [comment]
@andresriancho i used NodeGoat app for testing, it is already packaged with dockerfile

**Pull request closed without merging**
