### PR TITLE
Added gui support to the dockerfile.  Added a little explanation in the ...

### PR DESCRIPTION
**Pull request by aking1012**
...readme.

### CODE REVIEW

**Comment by andresriancho** [comment]
@aking1012 were you able to make the GUI part work? It doesn't work for me, even with things like:

```
docker run -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix andresriancho/w3af /home/w3af/w3af/w3af_gui
```

Which are "cheating" the ssh forwarding and won't work (I believe) with boot2docker

Could you help me out to complete the `w3af_gui_docker` script? Thanks!

**Comment by aking1012** [comment]
I'll give it a look.  I hadn't gotten around to piping it through
boot2docker container inception thing.  I ran the GUI part from a VM
ssh-ing to the docker container that had the X packages.

**Comment by andresriancho** [comment]
@aking1012 any ideas on why it isn't working as-is with the new w3af_gui_docker script?

**Comment by aking1012** [comment]
Haven't had time to even look at the branch.  I'm on a 3 day weekend this
weekend though.  I'll do a fresh pull and check it out at some point this
weekend.

**Comment by aking1012** [comment]
I haven't used the docker api that way, so I'm not sure.  I'ld have to poke
it a bit.  I'll look at it more deeply, but I'm trying to make a stretch
goal on something else too this weekend.

**Comment by andresriancho** [comment]
I've got some time I could use for this now, let me know if you want me to finish this one

**Comment by aking1012** [comment]
If you'ld like to plow through it, totally fine by me.  Something I see
coming up with boot2docker is, even if you get the docker api setup working
with the ssh -X passing, you still have to get that ssh connection passed
through the "docker container VM".  Just something I see coming up as an
issue.

**Comment by andresriancho** [comment]
I finally left this unfinished, I'm actually working on #7503 , maybe when I finish I'll come back, but feel free to take over at any time.

**Comment by aking1012** [comment]
Cool.  Thanks for the confidence.  I'm still grappling with another
problem, but it could get relevant as an escape from some circular logic
problem.

**Comment by andresriancho** [comment]
Closing this PR since it because really outdated with the code I've done at https://github.com/andresriancho/w3af/tree/aking1012-develop/extras . I'm planning to finish that code (at least the console part) today at https://github.com/andresriancho/w3af/issues/2612

**Pull request closed without merging**
