### PR TITLE
Fix file permissions

### PR DESCRIPTION
**Pull request by LocutusOfBorg**

### CODE REVIEW

**Comment by andresriancho** [comment]
Thanks for the PR! :+1: 

Check https://github.com/andresriancho/w3af/blob/master/circle.yml , there are some files which do require 755, for example:

 * w3af/core/controllers/ci/nosetests_wrapper/main.py
 * w3af/core/controllers/ci/setup_moth.py
 * w3af/core/controllers/ci/teardown_moth.py

Others might also require that permission.

Please review all files and make sure that removing 755 won't break anything.

Closing this PR since all PRs should be made against the develop branch, not master.

**Comment by andresriancho** [comment]
The fix is valuable, so please don't hesitate to open a new PR for the develop branch with the updated changes.

**Comment by LocutusOfBorg** [comment]
sorry I do not think I have enough knowledge to look at them all :)

I hope you can clean up the pr, because I can't learn the whole w3af code for this (I'm going to make it go into debian again)

**Comment by andresriancho** [comment]
Will cleaup myself.

**Comment by andresriancho** [comment]
https://github.com/andresriancho/w3af/commit/4cd008c846b87a2d232194560edae3470f6349f1

**Comment by andresriancho** [comment]
Done! Thanks.

**Pull request closed without merging**
